name: Create PR against main branch whenever code is pushed to dev

# Triggers on code push to main branch of the repository
on:
  push:
    branches:
      - dev

env:
  OWNER: TB-EIT
  REPO: interview-prepper
  PR_SOURCE: dev
  PR_TARGET: main
  GH_TOKEN: ${{ secrets.PR_CREATE_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create PR
        id: create-pr
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
            -f title='${{ env.OWNER }}/${{ env.REPO }} Auto PR' \
            -f body='Please pull these awesome changes in!' \
            -f head='${{ env.PR_SOURCE }}' \
            -f base='${{ env.PR_TARGET }}'
        continue-on-error: true # This is dirty, but helps to ignore "PR already exists" issue.