name: Create PR Workflow
on:
  repository_dispatch:
    types: [trigger-pr-creation]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "Automated Pull Request"
          body: |
            This is an automated pull request.
          token: ${{ secrets.GITHUB_TOKEN }}
