name: Create PR against main branch whenever code is pushed to develop

# Triggers on code push to main branch of the repository
on:
  push:
    branches:
      - dev

env:
  OWNER: PrinceAkrong
  REPO: POC-AUTO-PR
  PR_SOURCE: dev
  PR_TARGET: main
  GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create PR
        id: create-pr
        run: |
          gh api "/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls" \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -f title="${{ env.OWNER }}/${{ env.REPO }} Auto PR" \
            -f body="Please pull these awesome changes in!" \
            -f head="${{ env.PR_SOURCE }}" \
            -f base="${{ env.PR_TARGET }}"
            # Automatically approve the PR
            pull_request_url=$(echo "$response" | jq -r .url)
            pr_number=$(echo "$response" | jq -r .number)
  
      - name: Wait for Checks
        if: success()
        run: |
            sleep 10  # Waiting for checks to complete (adjust timing if needed)
  
      - name: Automatically Approve PR
        if: success()
        run: |
            gh pr review $pr_number --approve --body "Automatically approved" -R ${{ env.OWNER }}/${{ env.REPO }} --token ${{ secrets.MY_ACCESS_TOKEN }}
  
      - name: Auto-Merge PR
        if: success()
        run: |
            gh pr merge $pr_number --squash -R ${{ env.OWNER }}/${{ env.REPO }} --token ${{ secrets.MY_ACCESS_TOKEN }}
        continue-on-error: true
      