name: Demo to create automatic PR
on:
  push:
    branches:
      - auto-pr-branch  # Replace 'main' with your branch name

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "new-feature-branch"  # Replace with your new branch name
          base: main  # Replace 'main' with your base branch name
          title: "Automated Pull Request"
          body: |
            This is an automated pull request.
          token: ${{ secrets.GITHUB_TOKEN }}

          