name: Build Workflow and Trigger create-pull-request

on:
  push:
    branches:
      - auto-pr-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code   
        uses: actions/checkout@v2
        
      - name: set up java env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build completed
        id: build_completed
        run: echo "Build completed successfully"

      - name: Trigger create-pull-request workflow
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/PrinceAkrong/POC-AUTO-PR/actions/workflows/6900879596/dispatches \
            -d '{"ref":"main"}'
