name: Build Workflow and create auto PR

on:
  push:
    branches:
      - auto-pr-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code   
        uses: actions/checkout@v2
        
      - name: set up java env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/auto-pr-branch'
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Replace MY_ACCESS_TOKEN with your secret name
        run: |
          REPO_URL="https://api.github.com/repos/PrinceAkrong/POC-AUTO-PR/pulls"
          
          # Create a JSON payload for the pull request
          TITLE="Automatic PR from auto-pr-branch to main"
          HEAD="auto-pr-branch"
          BASE="main"
          
          DATA="{\"title\":\"$TITLE\",\"head\":\"$HEAD\",\"base\":\"$BASE\"}"
          
          # Make a POST request to create the pull request
          RESPONSE=$(curl -X POST -H "Authorization: token $ACCESS_TOKEN" -H "Content-Type: application/json" -d "$DATA" $REPO_URL)
          
          # Check the response for errors
          HTML_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          if [ "$HTML_URL" != "null" ]; then
            echo "Pull request created successfully: $HTML_URL"
          else
            echo "Failed to create pull request. Response: $RESPONSE"
            exit 1
          fi
