name: Build Workflow and create auto PR

on:
  push:
    branches:
      - auto-pr-branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Using the default GitHub token available in actions

    steps:
      - name: checking out code   
        uses: actions/checkout@v2
        
      - name: set up java env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/auto-pr-branch'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/OWNER/REPO/pulls \
            -f title='Amazing new feature' \
            -f body='Please pull these awesome changes in!' \
            -f head='octocat:new-feature' \
            -f base='master'
