name: Build Workflow and create auto PR

on:
  push:
    branches:
      - auto-pr-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code   
        uses: actions/checkout@v2
        
      - name: set up java env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/auto-pr-branch'
        env:
          ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }} # Replace MY_ACCESS_TOKEN with your secret name
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/OWNER/REPO/pulls \
            -f title='Amazing new feature' \
            -f body='Please pull these awesome changes in!' \
            -f head='octocat:new-feature' \
            -f base='main'
