name: Build Workflow and create auto PR

on:
  push:
    branches:
      - auto-pr-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code   
        uses: actions/checkout@v2
        
      - name: set up java env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/auto-pr-branch'
        env:
          ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }} # Replace MY_ACCESS_TOKEN with your secret name
        run: |
          curl --http1.1 -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/pulls \
            -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'
