name: Demo to create automatic PR
on:
  push:
    branches: [ "auto-pr-branch" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code   
        uses: actions/checkout@v3
        
      - name: set up java env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: grant permission
        run: chmod +x $GITHUB_WORKSPACE/.github/workflows/dradlew

      - name: build action
        run: $GITHUB_WORKSPACE/.github/workflows/dradlew build
